name: EnchantBottleCompression
version: ${project.version}
main: ubiquitaku.enchantbottlecompression.EnchantBottleCompression
api-version: 1.16
commands:
  ebottole:
    description: ((┗(┏ヽ ՞ةڼ◔`┛)┓))ア゛ア゛ア゛ア゛ア゛ア゛ア
permissions:
  ebc.use:
    default: '*'
  ebc.op:
    default: op